export const categoryMessages: { [key: string]: string } = {
    "body": "Touch this part of your body",
    "cat face": "Meow! You're a cat lover ?!",
    "clothing": "Dress to impress, even in emojis!",
    "creature-face": "WHAT HAPPENED TO YOUR FACE?",
    "emotion": "Emotions make us human... paham!",
    "face negative": "Negativity is like a flat tire until you change it, you’re going nowhere.",
    "face neutral": "Staying cool and neutral!",
    "face positive": "A cheerful heart is good medicine!",
    "face role": "Mandor mah kuatttt. Doing special role eh?",
    "face sick": "Oh no, feeling under the weather?",
    "family": "Family first, even in emoji form!",
    "monkey face": "Ooh ooh ah ah! A monkey appears!",
    "person": "Yeah, probably this is someone you want to meet",
    "person activity": "Time for some action!",
    "person gesture": "Gestures say a lot without words!",
    "person role": "Your future job",
    "skin tone": "Emojis come in all shades!",
  };